name: Unity - Build

on: 
  push:
      branches:
        - main

jobs:
  build:
    name: Build project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout (without LFS)
      - name: Checkout repository
        uses: actions/checkout@v2

      # Git LFS
      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS cache
        uses: actions/cache@v2
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache
      - uses: actions/cache@v2
        with:
          path: ModelViewer/Library
          key: Library-${{ hashFiles('ModelViewer/Assets/**', 'ModelViewer/Packages/**', 'ModelViewer/ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
#       - name: Run tests
#         uses: game-ci/unity-test-runner@v2
#         env:
#           UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
#         with:
#           githubToken: ${{ secrets.GITHUB_TOKEN }}

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: ./ModelViewer/

      # Output
      - uses: actions/upload-artifact@v3
        with:
          name: Build
          path: ~/artifact
          
# UPLOAD BUILD TO AZURE CONTAINER
  upload:
    name: Upload to Azure Storage
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Load artifact from previous job
      # - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Build
          #path: ~/artifact
      - name: List files
        run: ls -R
        working-directory: ~/artifact

      # Upload to azure blob storage
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: ~/artifact
          container_name: model-viewer
          connection_string: ${{ secrets.BLOB_CONNECTION_STRING }}
          overwrite: 'true'

